image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run win32

after_build:
  - ps: ls dist\electron-mat\Packaged\*

artifacts:
  - path: dist/electron-mat/Packaged/*exe
    name: executable
  - path: dist/electron-mat/UnPackaged/resources/app.asar
    name: asar

deploy:
  release: wordfreq-v$(appveyor_build_version)
  description: '第一版'
  provider: GitHub
  auth_token:
    secure: 8TyPdI8JenHl/cXkEPYiuAY+4Arb8bsp+pJ6kkCAljhrTcXaJe3HH+JPrMSFyqrl
  artifact: executable
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false        # deploy on tag push only

test: off
