image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run win32

after_build:
  - ps: ls dist\electron-mat\*

test: off
